### ISSUE TITLE
How to check against the cookie

### ISSUE THREAD

**Issue by ghost** [izolate/agegate#7]
How to check against the cookie so the gate isn't displayed for users who already answered it?

**Comment by izolate** [comment]
Hi @ghost - I'm sorry for the slow response. I've just released [v4.0.0](https://github.com/izolate/agegate/releases/tag/v4.0.0), which is a complete rewrite of this library, and therefore I'm closing this issue because it no longer applies to the current version.

I hope the new version meets your needs.
